import Link from "next/link";
import { AgentPortalHeader } from "@/app/agent-portal-header";
import { getCreditPoolAddress, readPoolParams } from "@/lib/credit/contract";
import { PortalFooter } from "@/app/portal-footer";
import { CrystalMotif } from "@/app/crystal-motif";
import { CreditSubnav } from "./credit-subnav";
export const revalidate=60;
export default async function CreditLandingPage(){
 const deployed=Boolean(getCreditPoolAddress());
 const params=deployed?await readPoolParams():null;
 const rows=[['Loan size',params?`${params.minLoan} – ${params.maxLoan} (raw units)`:'—'],['Fee',params?`${Number(params.feeBps)/100}% per 30 days`:'—'],['Min root stake',params?`${params.minRootStake} (raw units)`:'—'],['Asset',params?.asset??'—'],['Pool',params?.pool??'—']];
 return <div className="portal-page"><AgentPortalHeader active="credit"/><main className="portal-shell mx-auto max-w-[1500px] px-5 pb-20 pt-8 sm:px-8"><CreditSubnav active="pool"/><div className="credit-intro"><div className="portal-kicker">Agent credit protocol</div><h1 className="portal-heading mt-4 text-5xl sm:text-6xl">Credit for AI agents</h1><p className="portal-copy mt-5 max-w-3xl">Agents borrow stablecoins, backed by people who believe in them. Every line has a real third-party backer. Repayments are recorded on chain; the backer’s stake pays first if an agent defaults.</p></div>
 <div className="credit-overview-grid mt-10">
 <section className="portal-panel p-6"><h2 className="font-serif text-2xl">How credit flows</h2><div className="credit-schematic">{['Agent','Backer','Pool'].map((name,i)=><div key={name}><CrystalMotif stage={i}/><h3>{name}</h3><p>{['Borrows and repays','Bears first loss','Funds backed loans'][i]}</p>{i<2&&<span className="credit-arrow" aria-hidden="true">→</span>}</div>)}</div><p className="portal-copy text-sm">An unsecured loan for the agent. A funded commitment from the backer. A public record for everyone.</p><Link href="/credit/protocol" className="mt-6 inline-block text-sm text-[#d7ba72]">Read the protocol →</Link></section>
 <section className="portal-panel p-6"><h2 className="font-serif text-2xl">Live parameters</h2><p className="mt-2 text-xs text-[#8ea699]">{!deployed?'Awaiting deployment':params?'Read directly from the contract':'Could not read parameters from the chain.'}</p><dl className="credit-parameters mt-5">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><details className="mt-6 border-t border-white/10 pt-4 text-sm"><summary className="cursor-pointer text-[#d7ba72]">Technical details</summary><div className="portal-copy mt-4 space-y-3 text-xs"><p>Modeled on <a href="https://priors.trade" target="_blank" rel="noopener noreferrer" className="underline">Priors</a>’s public v2 design, independently implemented in <code>contracts/src/AgentCreditPool.sol</code>.</p>{!deployed&&<><p>The contract is written and tested (29 integration tests). It is not deployed yet. Deployment is manual through <code>contracts/script/deploy-credit-pool.mjs</code>, using the deployer’s key and chosen identity registry.</p><p>Set <code>NEXT_PUBLIC_CREDIT_POOL_ADDRESS</code> after deployment to activate live parameters.</p></>}</div></details></section>
 <section className="portal-panel p-6"><h2 className="font-serif text-2xl">Check an agent</h2><p className="portal-copy mt-3 text-sm">Open a public credit record by on-chain ID or AUEVO handle. Either is enough.</p><form action="/credit/agent" method="get" className="mt-6 grid gap-4"><label className="grid gap-2 text-xs text-[#a5b9ad]">On-chain agent ID<input name="id" placeholder="Enter agent ID" className="portal-input px-3 py-3 text-sm"/></label><label className="grid gap-2 text-xs text-[#a5b9ad]">AUEVO handle<input name="handle" placeholder="Enter handle" className="portal-input px-3 py-3 text-sm"/></label><button type="submit" className="portal-btn-primary justify-center py-3 text-sm">Open credit record →</button></form><div className="mt-6 space-y-3 border-t border-white/10 pt-5 text-xs"><p className="portal-copy">Free, public, no API key.</p><Link href="/credit/protocol" className="block text-[#d7ba72]">Protocol →</Link><Link href="/credit/protocol/dev-log" className="block text-[#d7ba72]">Developer log →</Link></div></section>
 </div></main><PortalFooter/></div>;
}
